[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "fouille"
version = "0.0.1"
description = "End of term project"
authors = [
  { name = "César Pichon", email = "cesarpichon@gmail.com" },
  { name = "Damien Biguet", email = "ninuje@gmail.com" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License"
]
requires-python = "~=3.12.0"


[tool.ruff]
respect-gitignore = false
line-length = 122
src = ["fouille"]
include = ["pyproject.toml", "fouille/**/*.py", "data/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["fouille"]
force-sort-within-sections = true

[tool.ruff.format]
indent-style = "tab"
